services:
  - type: web
    name: appointment
    env: docker
    repo: https://github.com/Djsensei1/laravel
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: APP_KEY
        sync: false
